export const enum useStateKeys {
    PROMPT_VARIABLES = 'PROMPT_VARIABLES',
    RAW_PROMPT = 'RAW_PROMPT',
    PARSED_PROMPT = 'PARSED_PROMPT',
    PREVIEW_PROMPT = 'PREVIEW_PROMPT',
    SELECTED_MODEL = 'SELECTED_MODEL',
    COMPLETION = 'COMPLETION',
    LOADING_COMPLETION = 'LOADING_COMPLETION'
}